### ISSUE TITLE
Is writeLoop necessary?

### ISSUE THREAD

**Issue by alanshaw** [mcollina/fast-write-atomic#4]
It's only called with `offset` 0, which means that `bytesWritten` will always equal `content.length` and it'll never call `writeLoop` - right?

That said, if `fs.write` doesn't write all the bytes you ask it to write then I think there's an error in the conditional here:

https://github.com/mcollina/fast-write-atomic/blob/e97a17b95568229e06e7e43853690f56c530ce42/index.js#L30

Which should be:

```js
if (bytesWritten !== content.length - offset) {
```

**Comment by mcollina** [comment]
> It's only called with offset 0, which means that bytesWritten will always equal content.length and it'll never call writeLoop - right?


It's needed because `fs.write` could potentially write only `n` bytes off the buffer https://github.com/mcollina/fast-write-atomic/blob/master/index.js#L23, so we should loop until the buffer is exhausted.

**Comment by alanshaw** [comment]
Gotcha, that behaviour wasn't clear when I was reading the [docs for `fs.write`](https://nodejs.org/dist/latest/docs/api/fs.html#fs_fs_write_fd_buffer_offset_length_position_callback).

**Comment by mcollina** [comment]
I found that out the hard way.
