### ISSUE TITLE
Still experimental?

### ISSUE THREAD

**Issue by aral** [mcollina/fast-write-atomic#8]
Hey @mcollina,

First off, thanks for sharing this. Quick question: I noticed in the readme that the module is marked “experimental” but has been up for about two years. Would you still consider it experimental / are you using it yourself these days? 

I had a quick look through the code while comparing it to [write-file-atomic](https://github.com/npm/write-file-atomic) and, from what I can see, they approach the atomicity issue in the same way (with the latter doing a few more things like queuing requests to overwrite the same while, which I don’t need as I’m already doing that myself). Performance-wise, I’m also seeing similar results.

Just trying to decide between the two and my gut feeling is to go with this one as it’s more focused (`less code = better` in my book). Would value your thoughts. Please feel free to ignore if you’re busy :)

**Comment by mcollina** [comment]
It's experimental because it's not as battle tested as the other one. If you have performance issues, use this one ;).
